Repository pace-neutrons/Herbert, pull requests merged in 2021-04, with the labels that each got.

#339 Update herbert on template
  CMakeLists.txt
  _test/CMakeLists.txt
  admin/CMakeLists.txt
  admin/herbert_on.m.template
Labels: do-not-merge

#342 Replace build tests with build testing
  CMakeLists.txt
  _LowLevelCode/cpp/CMakeLists.txt
  admin/CMakeLists.txt
  tools/build_config/build.ps1
  tools/build_config/build.sh
Labels: Build, tech-debt

#325 Change Jenkins config path
  _test/common_functions/MPI_Test_Common.m
  _test/test_mpi_wrappers/FakeJenkins4Tests.m
  _test/test_mpi_wrappers/MessagesFileBasedMPI_mirror_tester.m
  _test/test_mpi_wrappers/test_cluster_wrapper.m
  _test/test_mpi_wrappers/test_exchange_FileBasedMPI.m
  _test/test_mpi_wrappers/test_job_dispatcher_common_methods.m
  herbert_core/admin/is_jenkins.m
  herbert_core/admin/tmp_dir.m
  herbert_core/classes/MPIFramework/@MessagesFilebased/private/copy_existing_config_to_remote_.m
  herbert_core/configuration/@config_store/config_store.m
  herbert_core/utilities/misc/make_config_folder.m
  herbert_core/utilities/misc/try_to_create_folder.m
Labels: CI, Testing

#340 Add a lazy fix to handle MATLAB strings in equal_to_tol
  herbert_core/utilities/maths/equal_to_tol.m
Labels: bug
